# Generated by Django 4.1.2 on 2022-10-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mamonts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=2048)),
                ('password', models.CharField(max_length=2048)),
                ('token', models.CharField(max_length=2048)),
                ('first_name', models.CharField(max_length=2048)),
                ('last_name', models.CharField(max_length=2048)),
            ],
        ),
    ]
